controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
#loggedOut:
    #path: /loggedOut
    #controller: App\Controller\Controller_loggedOut::login
